import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "QuotVid Terms of Service — rules and guidelines for using the QuotVid platform.",
  alternates: { canonical: `${SITE_URL}/terms` },
  robots: { index: true, follow: true },
};

const sections = [
  { title: "1. Acceptance of Terms", content: `By creating an account or using QuotVid ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.\n\nThese Terms apply to all users of quotvid.com and app.quotvid.com.` },
  { title: "2. Description of Service", content: `QuotVid is an AI-powered quote video generation platform. The Service allows users to:\n- Set content personas (niche, language, style preferences)\n- Generate AI-written quote content\n- Render and download professional short-form video content\n- Access videos through a web-based dashboard` },
  { title: "3. Account Registration", content: `To use QuotVid, you must:\n- Provide accurate and complete registration information\n- Maintain the security of your password\n- Be at least 16 years of age\n- Not create accounts for others without their permission\n\nYou are responsible for all activity that occurs under your account.` },
  { title: "4. Acceptable Use", content: `You agree not to use QuotVid to:\n- Generate content that is defamatory, hateful, or discriminatory\n- Infringe on the intellectual property rights of others\n- Distribute spam or unsolicited communications\n- Attempt to reverse-engineer or scrape the Service\n- Use the Service for any illegal purpose\n- Impersonate any person or entity\n\nWe reserve the right to suspend or terminate accounts that violate these terms.` },
  { title: "5. Intellectual Property", content: `Your content: You own the videos you generate using QuotVid. You are granted a perpetual, royalty-free license to use, distribute, and monetize videos generated through the Service.\n\nOur platform: The QuotVid platform, including its AI models, templates, code, and branding, remains the exclusive property of QuotVid. You may not copy, modify, or distribute the platform itself.\n\nAI-generated content: Quote text generated by our AI is provided for your use. We do not claim ownership of generated content.` },
  { title: "6. Payment Terms", content: `Payments are processed by Lemon Squeezy LLC, our payment processor.\n\nFree Trial: A 7-day free trial is available to new users. No credit card is required to start a trial.\n\nSubscriptions: Monthly and annual subscriptions renew automatically until cancelled. You may cancel at any time from your billing settings.\n\nLifetime Deal: One-time payment plans grant lifetime access to the plan features at time of purchase.\n\nRefund Policy: We offer a 7-day money-back guarantee on paid plans. Contact us at hello@quotvid.com within 7 days of your payment.` },
  { title: "7. Service Availability", content: `We aim to maintain high availability but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to maintenance, updates, or factors outside our control.\n\nWe are not liable for losses caused by Service interruptions.` },
  { title: "8. AI-Generated Content Disclaimer", content: `QuotVid uses AI to generate quote content. While we strive for quality and originality, we do not guarantee that generated content is:\n- Factually accurate\n- Free from unintended similarity to existing content\n- Suitable for all audiences or purposes\n\nYou are responsible for reviewing generated content before publishing.` },
  { title: "9. Limitation of Liability", content: `To the maximum extent permitted by law, QuotVid is not liable for:\n- Indirect, incidental, or consequential damages\n- Loss of revenue, data, or business opportunities\n- Damages arising from use or inability to use the Service\n\nOur total liability shall not exceed the amount you paid for the Service in the 3 months preceding the claim.` },
  { title: "10. Termination", content: `We may suspend or terminate your account if you violate these Terms. You may delete your account at any time from your profile settings.\n\nUpon termination, your access to the Service ends. Generated videos you have already downloaded remain yours.` },
  { title: "11. Changes to Terms", content: `We may update these Terms from time to time. We will notify you of material changes by email or in-app notice. Continued use of the Service after changes constitutes acceptance.` },
  { title: "12. User-Submitted Video Content", content: `Paid plan users may submit URLs to third-party video platforms (YouTube, TikTok, Instagram, Vimeo, Facebook, etc.) to use as video backgrounds. By submitting a URL, you confirm that:\n- You have the legal right to use the referenced video content for your purposes\n- Your use complies with the terms of service of the originating platform\n- The content does not infringe any copyright, trademark, or other intellectual property right\n\nQuotVid stores a short clip (up to 60 seconds) on Cloudflare R2 for the sole purpose of rendering your generated videos. You remain solely responsible for ensuring that any third-party video content you reference is used lawfully.\n\nQuotVid reserves the right to remove any stored content that is reported as infringing or that violates these Terms. Repeated violations may result in account suspension.` },
  { title: "13. Governing Law", content: `These Terms are governed by the laws applicable to the jurisdiction where QuotVid operates. Disputes shall be resolved through good-faith negotiation first, then binding arbitration if necessary.` },
  { title: "14. Contact", content: `For questions about these Terms:\nhello@quotvid.com\nquotvid.com` },
];

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main>
        <section className="bg-section-dark pt-28 pb-10 sm:pt-32 sm:pb-12 md:pt-40">
          <div className="container mx-auto max-w-3xl px-3 sm:px-4 md:px-8">
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight md:text-4xl">Terms of Service</h1>
            <p className="mt-3 text-sm text-muted-foreground">Last Updated: March 2026 · Effective Date: March 2026</p>
          </div>
        </section>
        <section className="bg-section-light py-12 sm:py-16">
          <div className="container mx-auto max-w-3xl px-3 sm:px-4 md:px-8 space-y-10 sm:space-y-12">
            {sections.map((s) => (
              <div key={s.title}>
                <h2 className="mb-4 text-lg sm:text-xl font-bold text-light-heading">{s.title}</h2>
                <p className="text-xs sm:text-sm leading-relaxed text-light-body whitespace-pre-line">{s.content}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
