import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service — Social Media Auto-Posting, Acceptable Use & Billing | QuotVid",
  description:
    "QuotVid's Terms of Service covering social media platform integrations (YouTube, Instagram, TikTok, Pinterest, Facebook), acceptable use of auto-posting, subscription terms, and content responsibilities.",
  alternates: { canonical: `${SITE_URL}/terms` },
  robots: { index: true, follow: true },
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By creating an account or using QuotVid ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.\n\nThese Terms apply to all users of quotvid.com and app.quotvid.com.`,
  },
  {
    title: "2. Description of Service",
    content: `QuotVid is an AI-powered quote video generation platform with social media auto-posting. The Service allows users to:\n- Set content personas (niche, language, style preferences)\n- Generate AI-written quote content\n- Render and download professional short-form video content (1080×1920)\n- Automatically post videos to YouTube, Instagram, TikTok, Pinterest, and Facebook on a user-defined schedule\n- Access videos and post history through a web-based dashboard`,
  },
  {
    title: "3. Account Registration",
    content: `To use QuotVid, you must:\n- Provide accurate and complete registration information\n- Maintain the security of your password\n- Be at least 16 years of age\n- Not create accounts for others without their permission\n\nYou are responsible for all activity that occurs under your account.`,
  },
  {
    title: "4. Acceptable Use",
    content: `You agree not to use QuotVid to:\n- Generate content that is defamatory, hateful, or discriminatory\n- Infringe on the intellectual property rights of others\n- Distribute spam or unsolicited communications\n- Attempt to reverse-engineer or scrape the Service\n- Use the Service for any illegal purpose\n- Impersonate any person or entity\n\nWe reserve the right to suspend or terminate accounts that violate these terms.`,
  },
  {
    title: "5. Intellectual Property",
    content: `Your content: You own the videos you generate using QuotVid. You are granted a perpetual, royalty-free license to use, distribute, and monetize videos generated through the Service.\n\nOur platform: The QuotVid platform, including its AI models, templates, code, and branding, remains the exclusive property of QuotVid. You may not copy, modify, or distribute the platform itself.\n\nAI-generated content: Quote text generated by our AI is provided for your use. We do not claim ownership of generated content.`,
  },
  {
    title: "6. Social Media Platform Integrations",
    content: `6.1 Authorization\nWhen you connect a social media account (YouTube, Instagram, TikTok, Pinterest, or Facebook), you authorize QuotVid to post content to that account on your behalf using the platform's official OAuth 2.0 login system. You may revoke this authorization at any time by disconnecting the platform in your Integrations screen or by revoking access directly in the platform's security settings.\n\n6.2 Platform Terms of Service Compliance\nBy using QuotVid to post to any platform, you agree to comply with that platform's own terms of service and community guidelines, including:\n- YouTube Terms of Service\n- Meta Platform Terms and Instagram Community Guidelines\n- TikTok Terms of Service\n- Pinterest Terms of Service\n- Facebook Terms of Service\n\nYou are responsible for ensuring that content you post via QuotVid complies with each platform's rules.\n\n6.3 Content Responsibility\nQuotVid is a technical intermediary — we post content on your behalf, but you are solely responsible for the content that is posted. This includes AI-generated quotes, captions, and any uploaded media.\n\n6.4 No Spam\nUsing QuotVid's auto-posting feature to post spam, unsolicited content, or content that violates a platform's spam policies is strictly prohibited and will result in immediate account suspension.\n\n6.5 Scope of Access\nQuotVid requests only the minimum permissions required to post your videos. We do not scrape audience data, follower lists, direct messages, video analytics, or any data beyond what is described in our Privacy Policy.\n\n6.6 Platform API Changes\nSocial media platforms may change their APIs, policies, or access requirements at any time. QuotVid is not responsible for interruptions to integrations caused by platform-side changes. We will make reasonable efforts to maintain integrations but cannot guarantee uninterrupted service for any specific platform.\n\n6.7 No Guarantee of Posting Success\nQuotVid will retry failed posts up to 5 times. We are not liable for posts that fail due to platform errors, account restrictions, content policy rejections, or connectivity issues. You can view post status in your dashboard and retry manually if needed.`,
    link: { text: "View platform integration details →", href: "/integrations" },
  },
  {
    title: "7. Acceptable Use of Auto-Posting",
    content: `When using auto-posting, you confirm that:\n- You own or have the right to use all content in posted videos (including uploaded backgrounds, audio, and logos)\n- You are not using auto-posting to impersonate another person, brand, or public figure\n- You are not using auto-posting to artificially inflate metrics (views, likes, engagement)\n- You are not posting content that violates any applicable law`,
  },
  {
    title: "8. Payment Terms",
    content: `Payments are processed by Lemon Squeezy LLC, our payment processor.\n\nFree Trial: A free trial is available to new users (5 videos). No credit card is required to start.\n\nSubscriptions: Monthly and annual subscriptions renew automatically until cancelled. You may cancel at any time from your billing settings.\n\nLifetime Deal: One-time payment plans grant lifetime access to the plan features at time of purchase.\n\nRefund Policy: We offer a 7-day money-back guarantee on paid plans. Contact us at hello@quotvid.com within 7 days of your payment.`,
  },
  {
    title: "9. Video Retention",
    content: `AI-generated videos (AI Persona mode): Auto-deleted after 7 days. The expiry date is shown in your Generated Videos list. Download your favorites before they expire.\n\nCustom Studio videos: Stored indefinitely until you manually delete them.\n\nPosts on platforms: Videos already published to social media platforms remain there after deletion from QuotVid. To remove them from a platform, delete them directly on that platform.`,
  },
  {
    title: "10. User-Submitted Content",
    content: `You may upload background videos, images, and audio files. By uploading content, you confirm that:\n- You have the legal right to use the content for your purposes\n- Your use complies with the terms of service of any originating platform\n- The content does not infringe any copyright, trademark, or other intellectual property right\n\nQuotVid stores uploaded content on Cloudflare R2 for the sole purpose of rendering your generated videos. Repeated violations may result in account suspension.`,
  },
  {
    title: "11. AI-Generated Content Disclaimer",
    content: `QuotVid uses AI to generate quote content. While we strive for quality and originality, we do not guarantee that generated content is:\n- Factually accurate\n- Free from unintended similarity to existing content\n- Suitable for all audiences or purposes\n\nYou are responsible for reviewing generated content before publishing.`,
  },
  {
    title: "12. Service Availability",
    content: `We aim to maintain high availability but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to maintenance, updates, or factors outside our control.\n\nWe are not liable for losses caused by Service interruptions.`,
  },
  {
    title: "13. Limitation of Liability",
    content: `To the maximum extent permitted by law, QuotVid is not liable for:\n- Indirect, incidental, or consequential damages\n- Loss of revenue, data, or business opportunities\n- Damages arising from use or inability to use the Service\n- Failed, delayed, or rejected posts on social media platforms\n\nOur total liability shall not exceed the amount you paid for the Service in the 3 months preceding the claim.`,
  },
  {
    title: "14. Termination",
    content: `We may suspend or terminate your account if you violate these Terms. You may delete your account at any time from your profile settings.\n\nUpon termination, your access to the Service ends. Generated videos you have already downloaded remain yours. Platform connections are immediately revoked.`,
  },
  {
    title: "15. Changes to Terms",
    content: `We may update these Terms from time to time. We will notify you of material changes by email or in-app notice. Continued use of the Service after changes constitutes acceptance.`,
  },
  {
    title: "16. Governing Law",
    content: `These Terms are governed by the laws applicable to the jurisdiction where QuotVid operates. Disputes shall be resolved through good-faith negotiation first, then binding arbitration if necessary.`,
  },
  {
    title: "17. Contact",
    content: `For questions about these Terms:\nhello@quotvid.com\nquotvid.com`,
  },
];

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main>
        <section className="bg-section-dark pt-28 pb-10 sm:pt-32 sm:pb-12 md:pt-40">
          <div className="container mx-auto max-w-3xl px-3 sm:px-4 md:px-8">
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight md:text-4xl">Terms of Service</h1>
            <p className="mt-3 text-sm text-muted-foreground">Last Updated: April 2026 · Effective Date: April 2026</p>
          </div>
        </section>
        <section className="bg-section-light py-12 sm:py-16">
          <div className="container mx-auto max-w-3xl px-3 sm:px-4 md:px-8 space-y-10 sm:space-y-12">
            {sections.map((s) => (
              <div key={s.title}>
                <h2 className="mb-4 text-lg sm:text-xl font-bold text-light-heading">{s.title}</h2>
                <p className="text-xs sm:text-sm leading-relaxed text-light-body whitespace-pre-line">{s.content}</p>
                {"link" in s && s.link && (
                  <Link
                    href={s.link.href}
                    className="mt-3 inline-block text-xs sm:text-sm text-primary hover:underline"
                  >
                    {s.link.text}
                  </Link>
                )}
              </div>
            ))}
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
